// Query 1
LocationData
|project iss_position_longitude, iss_position_latitude, timestamp
| render scatterchart with ( kind=map )


// Query 2: which humans are in space right now?
AstronautsData
| top 1 by ['x-opt-enqueued-time']
| mv-expand people
| project Name= people.name, Craft=people.craft


// Query 3: ISS complete orbit
LocationData
| extend Timestamp =todatetime(timestamp)
| where Timestamp > ago(90m)
| project iss_position_longitude, iss_position_latitude, Timestamp











